T1/config/routes.rb
Rails.application.routes.draw do
  get 'search/show'
  get 'starships/show'
  get 'planets/show'
  get 'character/index'
  root 'movies#index' 

  get '/movies/:id', to: 'movies#show', as: :movie

  #get '/character/:url', to: 'character#index', as: :character
  get '/character/:url', to: 'character#show', as: :character

  get '/planets/:id', to: 'planets#show', as: :planets

  get '/starships/:id', to: 'starships#show', as: :starships

  get '/search/:id', to: 'search#show', as: :search

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

T1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

T1/app/models/movie.rb
class Movie < ApplicationRecord
end

T1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

T1/app/controllers/character_controller.rb
class CharacterController < ApplicationController

  def show
    pag = 'https://swapi.co/api/people/' + params[:url] + '/?format=json'
    @character = HTTParty.get(pag)
  end

end

T1/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

T1/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  #before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json

  def index
    @movies = HTTParty.get('https://swapi.co/api/films/?format=json')
  end

  #def index
   # @movies = Movie.new.films
  #end

  # GET /movies/1
  # GET /movies/1.json
  def show
    id = params[:id]
    url = 'https://swapi.co/api/films/' + id + '/?format=json'
    @movie = HTTParty.get(url)
    
  end

  # GET /movies/new

  # GET /movies/1/edit

  # POST /movies
  # POST /movies.json


end

T1/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def show
    pag = 'https://swapi.co/api/planets/' + params[:id] + '/?format=json'
    @planet = HTTParty.get(pag)
  end
end

T1/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def show
    if params[:search]
      @param = params[:search]
      #@people = HTTParty.get('https://swapi.co/api/people/?search=' + param)
      #@planets = HTTParty.get('https://swapi.co/api/planets/?search=' + param)
      #@starships = HTTParty.get('https://swapi.co/api/starships/?search=' + param)
      #@movies = HTTParty.get('https://swapi.co/api/films/?search=' + param)
    end
  end
end

T1/app/controllers/starships_controller.rb
class StarshipsController < ApplicationController
  def show
    pag = 'https://swapi.co/api/starships/' + params[:id] + '/?format=json'
    @starship = HTTParty.get(pag)
  end
end

T1/app/helpers/application_helper.rb
module ApplicationHelper
end

T1/app/helpers/character_helper.rb
module CharacterHelper
end

T1/app/helpers/home_helper.rb
module HomeHelper
end

T1/app/helpers/movies_helper.rb
module MoviesHelper
end

T1/app/helpers/planets_helper.rb
module PlanetsHelper
end

T1/app/helpers/search_helper.rb
module SearchHelper
end

T1/app/helpers/starships_helper.rb
module StarshipsHelper
end

T1/app/views/character/show.html.erb
<%= form_tag(search_path(:search), method: :get) do %>
<%= text_field_tag(:search, params[:search]) %>
<%= submit_tag('Search') %>
<% end %>

<center>
<h1><%= @character['name'] %></h1>

<% movies = [] %>
<% @character['films'].each do |f| %>
  <% f = f + '?format=json' %>
  <% film = HTTParty.get(f) %>
  <% movies.push(film) %>
  <% end %>

<% ships = [] %>
<% @character['starships'].each do |s| %>
<% s = s + '?format=json' %>
<% ship = HTTParty.get(s) %>
<% ships.push(ship) %>
<% end %>

<% w = @character['homeworld'] + '?format=json' %>
<% world = HTTParty.get(w) %>
<% id = world['url'] %>
<% id = id.split('/')[-1] %>

<table border="1">
    <thead>
        <tr>
            <th>Birth year</th>
            <th>Eye color</th>
            <th>Gender</th>
            <th>Hair color</th>
            <th>Height</th>
            <th>Mass</th>
            <th>Skin color</th>
            <th>Homeworld</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td><%= @character['birth_year'] %></td>
            <td><%= @character['eye_color'] %></td>
            <td><%= @character['gender'] %></td>
            <td><%= @character['hair_color'] %></td>
            <td><%= @character['height'] %></td>
            <td><%= @character['mass'] %></td>
            <td><%= @character['skin_color'] %></td>
            <td><%= link_to world['name'], planets_path(id) %></td>
        </tr>
    </tbody>
</table> 

<table border="1">
  <thead>
      <tr>
        <th>Films</th>
        <th>Starships</th>
        <th>created</th>
        <th>edited</th>
      </tr>
  </thead>

  <tbody>
      <tr>
        <td><% movies.each do |m|%>
            <li><%= link_to m['title'], movie_path(m['episode_id']) %></li>
          <% end %></td>
        <td><% ships.each do |s|%>
            <% id = s['url'] %>
            <% id = id.split('/')[-1] %>
            <li><%= link_to s['name'], starships_path(id) %></li>
            <% end %></td>
        <td><%= @character['created'] %></td>
        <td><%= @character['edited'] %></td>
      </tr>
  </tbody>
</table> 
</center>

T1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>T1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

T1/app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :episode_id %>
    <%= form.number_field :episode_id %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.date_select :release_date %>
  </div>

  <div class="field">
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>

  <div class="field">
    <%= form.label :producer %>
    <%= form.text_field :producer %>
  </div>

  <div class="field">
    <%= form.label :opening_crwl %>
    <%= form.text_field :opening_crwl %>
  </div>

  <div class="field">
    <%= form.label :species %>
    <%= form.text_field :species %>
  </div>

  <div class="field">
    <%= form.label :starships %>
    <%= form.text_field :starships %>
  </div>

  <div class="field">
    <%= form.label :vehicles %>
    <%= form.text_field :vehicles %>
  </div>

  <div class="field">
    <%= form.label :characters %>
    <%= form.text_field :characters %>
  </div>

  <div class="field">
    <%= form.label :planets %>
    <%= form.text_field :planets %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :created %>
    <%= form.text_field :created %>
  </div>

  <div class="field">
    <%= form.label :edited %>
    <%= form.text_field :edited %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

T1/app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

T1/app/views/movies/index.html.erb
<%= form_tag(search_path(:search), method: :get) do %>
<%= text_field_tag(:search, params[:search]) %>
<%= submit_tag('Search') %>
<% end %>

<center>
<h1>Star wars</h1>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Year</th>
            <th>Director</th>
            <th>Producer</th>
            <th>Episode</th>
            <th>More</th>
        </tr>
    </thead>

    <tbody>
        <% @movies['results'].each do |movie|%>
        <tr>
            <td><%= movie['title'] %></td>
            <td><%= movie['release_date'] %></td>
            <td><%= movie['director'] %></td>
            <td><%= movie['producer'] %></td>
            <td><%= movie['episode_id'] %></td>
            <td><%= link_to 'More info', movie_path(movie['episode_id']) %></td>
        </tr>
        <% end %>
    </tbody>
</table> 
</center>

T1/app/views/movies/show.html.erb
<%= form_tag(search_path(:search), method: :get) do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag('Search') %>
  <% end %>

<center>
<h1><%= @movie['title'] %></h1>

<% characters = [] %>
<% @movie['characters'].each do |c| %>
  <% c = c + '?format=json' %>
  <% character = HTTParty.get(c) %>
  <% characters.push(character) %>
  <% end %>

<% ships = [] %>
<% @movie['starships'].each do |s| %>
  <% s = s + '?format=json' %>
  <% ship = HTTParty.get(s) %>
  <% ships.push(ship) %>
  <% end %>

<% planets = [] %>
<% @movie['planets'].each do |p| %>
  <% p = p + '?format=json' %>
  <% planet = HTTParty.get(p) %>
  <% planets.push(planet) %>
  <% end %>


<table border="1">
    <thead>
        <tr>
            <th>Title</th>
            <th>Year</th>
            <th>Director</th>
            <th>Producer</th>
            <th>Episode</th>
            <th>Release date</th>
            <th>Starships</th>
            <th>Planets</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td><%= @movie['title'] %></td>
            <td><%= @movie['release_date'] %></td>
            <td><%= @movie['director'] %></td>
            <td><%= @movie['producer'] %></td>
            <td><%= @movie['episode_id'] %></td>
            <td><%= @movie['release_date'] %></td>
            <td><% ships.each do |s|%>
              <% id = s['url'] %>
              <% id = id.split('/')[-1] %>
              <li><%= link_to s['name'], starships_path(id) %></li>
              <% end %></td>
            <td><% planets.each do |p|%>
              <% id2 = p['url'] %>
              <% id2 = id2.split('/')[-1] %>
              <li><%= link_to p['name'], planets_path(id2) %></li>
              <% end %></td>
        </tr>
    </tbody>
</table> 

<table border="1">
  <thead>
      <tr>
        <th>Characters</th>
        <th>Opening crawl</th>
        <th>Created</th>
        <th>Edited</th>
        <th>Url</th>
      </tr>
  </thead>

  <tbody>
      <tr>
        <td><% characters.each do |char|%>
          <% b = char['url'] %>
          <% b = b.split('/') %>
        <li><%= link_to char['name'], character_path(b[-1]) %></li>
          <% end %></td>
        <td width="500"><%= @movie['opening_crawl'] %></td>
        <td><%= @movie['created'] %></td>
        <td><%= @movie['edited'] %></td>
        <td><%= @movie['url'] %></td>
      </tr>
  </tbody>
</table> 
</center>

T1/app/views/planets/show.html.erb
<%= form_tag(search_path(:search), method: :get) do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag('Search') %>
  <% end %>

<center>
    <h1><%= @planet['name'] %></h1>
    
    <% movies = [] %>
    <% @planet['films'].each do |f| %>
      <% f = f + '?format=json' %>
      <% film = HTTParty.get(f) %>
      <% movies.push(film) %>
      <% end %>
    
    <% people = [] %>
    <% @planet['residents'].each do |r| %>
    <% r = r + '?format=json' %>
    <% resident = HTTParty.get(r) %>
    <% people.push(resident) %>
    <% end %>
    
    <table border="1"> 
        <thead>
            <tr>
                <th>Name</th>
                <th>Diameter</th>
                <th>Rotation period</th>
                <th>Orbital period</th>
                <th>Gravity</th>
                <th>Population</th>
                <th>Climate</th>
                <th>Terrain</th>
                <th>Surface water</th>
            </tr>
        </thead>
    
        <tbody>
            <tr>
                <td><%= @planet['name'] %></td>
                <td><%= @planet['diameter'] %></td>
                <td><%= @planet['rotation_period'] %></td>
                <td><%= @planet['orbital_period'] %></td>
                <td><%= @planet['gravity'] %></td>
                <td><%= @planet['population'] %></td>
                <td><%= @planet['climate'] %></td>
                <td><%= @planet['terrain'] %></td>
                <td><%= @planet['surface_water'] %></td>
            </tr>
        </tbody>
    </table> 
    
    <table border="1">
      <thead>
          <tr>
            <th>Films</th>
            <th>Residents</th>
            <th>Edited</th>
          </tr>
      </thead>
    
      <tbody>
          <tr>
            <td><% movies.each do |m|%>
              <li><%= link_to m['title'], movie_path(m['episode_id']) %> </li>
              <% end %></td>
            <td><% people.each do |p|%>
                <% b = p['url'] %>
                <% b = b.split('/') %>
                <li> <%= link_to p['name'], character_path(b[-1]) %> </li>
                <% end %></td>
            <td><%= @planet['edited'] %></td>
          </tr>
      </tbody>
    </table> 
    </center>

T1/app/views/search/show.html.erb
<% @param %>
<% planets = HTTParty.get('https://swapi.co/api/planets/?search=' + @param) %>
<% peoples = HTTParty.get('https://swapi.co/api/people/?search=' + @param) %>
<% starships = HTTParty.get('https://swapi.co/api/starships/?search=' + @param) %>
<% films = HTTParty.get('https://swapi.co/api/films/?search=' + @param) %>

<%= form_tag(search_path(:search), method: :get) do %>
<%= text_field_tag(:search, params[:search]) %>
<%= submit_tag('Search') %>
<% end %>

<center>
<h2>Your search</h2>

<table border="1">
    <thead>
        <tr>
            <th>Films</th>
            <th>People</th>
            <th>Planets</th>
            <th>Starships</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td><% films['results'].each do |film|%>
                <% b = film['url'] %>
                <% b = b.split('/') %>
                <li><%= link_to film['title'], movie_path(b[-1]) %></li>
                <% end %></td>
            <td><% peoples['results'].each do |p|%>
                <% b = p['url'] %>
                <% b = b.split('/') %>
                <li><%= link_to p['name'], character_path(b[-1]) %></li>
                <% end %></td>
            <td><% planets['results'].each do |pl|%>
                <% b = pl['url'] %>
                <% b = b.split('/') %>
                <li><%= link_to pl['name'], planets_path(b[-1]) %></li>
                <% end %></td>
            <td><% starships['results'].each do |s|%>
                <% b = s['url'] %>
                <% b = b.split('/') %>
                <li><%= link_to s['name'], starships_path(b[-1]) %></li>
                <% end %></td>
        </tr>
    </tbody>
</table border="1"> 
</center>

T1/app/views/starships/show.html.erb
<%= form_tag(search_path(:search), method: :get) do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag('Search') %>
  <% end %>
  
<center>
    <h2><%= @starship['name'] %></h2>
    
    <% movies = [] %>
    <% @starship['films'].each do |f| %>
      <% f = f + '?format=json' %>
      <% film = HTTParty.get(f) %>
      <% movies.push(film) %>
      <% end %>
    
    <% pilots = [] %>
    <% @starship['pilots'].each do |r| %>
    <% r = r + '?format=json' %>
    <% pilot = HTTParty.get(r) %>
    <% pilots.push(pilot) %>
    <% end %>
    
    <table border="1">
        <thead>
            <tr>
                <th>Name</th>
                <th>Model</th>
                <th>Starship class</th>
                <th>Manufacturer</th>
                <th>Cost in credits</th>
                <th>Length</th>
                <th>Crew</th>
                <th>Passengers</th>
                <th>Max atmosphering spped</th>
                <th>Hyperdrive rating</th>
            </tr>
        </thead>
    
        <tbody>
            <tr>
                <td><%= @starship['name'] %></td>
                <td><%= @starship['model'] %></td>
                <td><%= @starship['starship_class'] %></td>
                <td><%= @starship['manufacturer'] %></td>
                <td><%= @starship['cost_in_credits'] %></td>
                <td><%= @starship['length'] %></td>
                <td><%= @starship['crew'] %></td>
                <td><%= @starship['passengers'] %></td>
                <td><%= @starship['max_atmosphering_speed'] %></td>
                <td><%= @starship['hyperdrive_rating'] %></td>
            </tr>
        </tbody>
    </table> 
    
    <table border="1">
      <thead>
          <tr>
            <th>MGLT</th>
            <th>Cargo capacity</th>
            <th>Consumables</th>
            <th>Films</th>
            <th>Pilots</th>
          </tr>
      </thead>
    
      <tbody>
          <tr>
            <td><%= @starship['MGLT'] %></td>
            <td><%= @starship['cargo_capacity'] %></td>
            <td><%= @starship['consumables'] %></td>
            <td><% movies.each do |m|%>
              <li><%= link_to m['title'], movie_path(m['episode_id']) %></li>
              <% end %></td>
            <td><% pilots.each do |p|%>
                <% b = p['url'] %>
                <% b = b.split('/') %>
                <li><%= link_to p['name'], character_path(b[-1]) %></li>
                <% end %></td>
          </tr>
      </tbody>
    </table> 
    </center>